# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20171222_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='add_tiem',
            new_name='add_time',
        ),
        migrations.RenameField(
            model_name='userleaavingmessage',
            old_name='add_tiem',
            new_name='add_time',
        ),
    ]
