# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0006_hotsearchwords'),
        ('user_operation', '0003_auto_20171222_2044'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together=set([('user', 'goods')]),
        ),
    ]
