# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0004_auto_20180219_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfav',
            name='goods',
            field=models.ForeignKey(help_text='商品id', on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='userleaavingmessage',
            name='file',
            field=models.FileField(help_text='上传文件', upload_to='message/images/', verbose_name='上传文件'),
        ),
    ]
